import { Feed } from "@/types/feed";
import { Bell, CopyMinus, CopyPlus, CreditCard, Settings } from "lucide-react";

export const feedData: Feed[] = [
  {
    id: 1,
    icon: Settings,
    type: "System",
    modul: "Production",
    title: "System update",
    desc: "Database backup completed",
    time: "10 minutes ago",
    color: "text-orange-500",
    bgColor: "bg-orange-100 dark:bg-orange-900/30",
  },
  {
    id: 2,
    icon: CreditCard,
    type: "Payment",
    modul: "Procurement",
    title: "Purchase 1.000 Paper",
    desc: "Pending purchase 1.000 paper",
    time: "1 hour ago",
    color: "text-purple-500",
    bgColor: "bg-purple-100 dark:bg-purple-900/30",
  },
  {
    id: 3,
    icon: Bell,
    type: "Notification",
    modul: "Product",
    title: "Low stock alert product Knife",
    desc: "Knife need added more quantity",
    time: "5 minutes ago",
    color: "text-red-500",
    bgColor: "bg-red-100 dark:bg-red-900/30",
  },
  {
    id: 4,
    icon: CopyPlus,
    type: "System",
    modul: "Inventory",
    title: "Movement inventory branch",
    desc: "Sidoarjo Branch send item Chair, Table, Radio From Surabaya Branch",
    time: "12 hour ago",
    color: "text-emerald-500",
    bgColor: "bg-emerald-100 dark:bg-emerald-900/30",
  },
  {
    id: 5,
    icon: CopyMinus,
    type: "System",
    modul: "Invetory",
    title: "Movement inventory branch",
    desc: "Surabaya Branch send item Chair, Table, Radio From Surabaya Branch",
    time: "12 hour ago",
    color: "text-yellow-500",
    bgColor: "bg-yellow-100 dark:bg--900/30",
  },
];
