import {
  TrendingUp,
  Users,
  Package,
  DollarSign,
  ShoppingCart,
  Factory,
  AlertTriangle,
  CheckCircle,
} from "lucide-react";
import { Statistic } from "@/types/statistic";

export const statisticsData: Statistic[] = [
  {
    id: "revenue",
    title: "Total Revenue",
    value: "$45,231",
    change: "+12.5%",
    trend: "up",
    icon: DollarSign,
    color: "from-green-500 to-emerald-600",
    bgColor: "bg-green-50 dark:bg-green-900/20",
    textColor: "text-emerald-600 dark:text-emerald-400",
    progress: 75,
  },
  {
    id: "orders",
    title: "Total Orders",
    value: "1,234",
    change: "+8.2%",
    trend: "up",
    icon: ShoppingCart,
    color: "from-blue-500 to-cyan-600",
    bgColor: "bg-blue-50 dark:bg-blue-900/20",
    textColor: "text-blue-600 dark:text-blue-400",
    progress: 60,
  },
  {
    id: "production",
    title: "Production",
    value: "856",
    change: "-3.1%",
    trend: "down",
    icon: Factory,
    color: "from-purple-500 to-pink-600",
    bgColor: "bg-purple-50 dark:bg-purple-900/20",
    textColor: "text-purple-600 dark:text-purple-400",
    progress: 45,
  },
  {
    id: "inventory",
    title: "Inventory Items",
    value: "2,450",
    change: "+5.4%",
    trend: "up",
    icon: Package,
    color: "from-orange-500 to-red-700",
    bgColor: "bg-orange-50 dark:bg-orange-900/20",
    textColor: "text-orange-600 dark:text-orange-400",
    progress: 82,
  },
];
